export default {
  frontend : [
    {title : 'Webpack Tree Shaking & Dynamic Import', fileUrl : '/frontend/webpack-treeshaking.md'},
    {title : '크롬 개발자 도구를 사용한 웹 성능분석', fileUrl : '/frontend/chrome-debugging-tool.md'},
    {title : 'Webpack을 통한 App Config 설정하기 (DefinePlugin, EnvironmentPlugin)', fileUrl : '/frontend/webpack-define-environment-plugin.md'},
    {title : 'npm에 모듈 배포하기 1', fileUrl : '/frontend/upload-to-npm-1.md'},
    {title : 'npm에 모듈 배포하기 2', fileUrl : '/frontend/upload-to-npm-2.md'},
    {title : 'npm에 모듈 배포하기 3', fileUrl : '/frontend/upload-to-npm-3.md'},
    {title : '크로스 도메인 해결방법', fileUrl : '/frontend/cross-domain.md'},
    {title : 'Vue-React-Angular 비교', fileUrl : '/frontend/vue-react-angular.md'},
    {title : 'viewport meta tag를 이용한 모바일 브라우저 레이아웃 설정', fileUrl : '/frontend/viewport-meta.md'},
    {title : 'AngularJS의 $watch, $apply, $digest 동작', fileUrl : '/frontend/angularjs-digest.md'},
    {title : 'Client side 렌더링과 Server side 렌더링', fileUrl : '/frontend/serverside-rendering.md'},
    {title : 'Gulp를 통한 model명 별로 빌드하기', fileUrl : '/frontend/gulp-model-build.md'},
    {title : 'Webpack 사용', fileUrl : '/frontend/webpack.md'},
    {title : 'MAC에서 IE테스트 환경 만들기', fileUrl : '/frontend/mac-ie-test.md'},
    {title : '크로스 브라우저 테스트를 위한 Browsersync', fileUrl : '/frontend/browser-sync.md'},
    {title : 'TDD & BDD', fileUrl : '/frontend/tdd-bdd.md'},
    {title : 'Jasmine & Karma', fileUrl : '/frontend/jasmine-karma.md'},
    {title : 'Git-Flow 브랜치', fileUrl : '/frontend/gitflow.md'},
    {title : 'Git repository 복사하기 (history 까지 통째로)', fileUrl : '/frontend/git-copy.md'},
    {title : 'Python으로 Model별 config.json 빌드', fileUrl : '/frontend/python-build.md'}
  ],
  vue : [
    {title : 'Vue.js의 Dynamic component 사용하기', fileUrl : '/vue/component-dynamic-import.md'},
    {title : 'Vue + Typescript 환경에서 Storybook 사용하기', fileUrl : '/vue/vue-typescript-storybook.md'},
    {title : 'Vue 컴포넌트 상속 (mixin과 extends)', fileUrl : '/vue/component-inherit.md'},
    //{title : 'Vue 서버사이드 렌더링', fileUrl : '/vue/vue-ssr.md'},
    {title : 'Vue에서 컴포넌트 강제 re-rendering 하기', fileUrl : '/vue/vue-force-re-render.md'},
    {title : 'Vuex 사용 및 Naming 컨벤션', fileUrl : '/vue/vuex-convention.md'},
    {title : 'Vue와 다른 framework 비교', fileUrl : '/vue/vue-else.md'},
    {title : 'AngularJS에서 Vue로 점진적으로 넘어가기 1', fileUrl : '/vue/migrate-from-angular-to-vue-1.md'},
    {title : 'AngularJS에서 Vue로 점진적으로 넘어가기 2', fileUrl : '/vue/migrate-from-angular-to-vue-2.md'},
    {title : 'AngularJS에서 Vue로 점진적으로 넘어가기 3', fileUrl : '/vue/migrate-from-angular-to-vue-3.md'},
    {title : 'AngularJS에서 Vue로 점진적으로 넘어가기 4', fileUrl : '/vue/migrate-from-angular-to-vue-4.md'},
    {title : 'IE에서 axios, vuex 사용시 에러 수정하기', fileUrl : '/vue/howto_use_vuex_inIE.md'},
  ],
  react : [
    {title : 'Jest, Enzyme 을 사용한 React 컴포넌트 테스트', fileUrl : '/react/jest-enzyme.md'},
    {title : 'MobX 사용 및 장단점', fileUrl : '/react/mobx-basic.md'},
    {title : 'React에서 MobX 사용하기', fileUrl : '/react/react-mobx.md'},
    {title : 'React Hooks', fileUrl : '/react/hooks.md'},
    {title : 'React Higher-Order Components (HOC)', fileUrl : '/react/hoc.md'},
    {title : 'Redux', fileUrl : '/react/redux.md'}
  ],
  typescript : [
    {title : 'Typescript Union & Intersection 타입', fileUrl : '/typescript/union-intersection-type.md'},
    {title : '타입단언(Type Assertion)과 타입가드(Type Guard)', fileUrl : '/typescript/type-assertion-type-guard.md'},
    {title : 'Vue에 Typescript 적용하기', fileUrl : '/typescript/vue-typescript.md'},
    {title : '제네릭(Generic) 타입', fileUrl : '/typescript/generic-type.md'},
    {title : 'd.ts 파일을 통한 타입선언', fileUrl : '/typescript/d.ts-file.md'},
    {title : 'tsconfig의 lib 옵션', fileUrl : '/typescript/tsconfig-lib.md'}
  ],
  javascript : [
    {title : 'Jquery의 Effect Queue', fileUrl : '/javascript/jquery-effectqueue.md'},
    {title : 'Mutable, Immutable Array 함수와 Spread 구문', fileUrl : '/javascript/mutable_array_spread.md'},
    {title : 'window.requestAnimationFrame()의 이해', fileUrl : '/javascript/requestanimationframe.md'},
    {title : 'Browser 이름 및 버전 체크 snippet', fileUrl : '/javascript/browser-check.md'},
    {title : 'MVW framework없이 SPA구현 1 (Page이동)', fileUrl : '/javascript/spa1.md'},
    {title : 'MVW framework없이 SPA구현 2 (Page구현)', fileUrl : '/javascript/spa2.md'},
    {title : 'MVW framework없이 SPA구현 3 (AMD)', fileUrl : '/javascript/spa3.md'},
    {title : 'MVW framework없이 SPA구현 4 (Component)', fileUrl : '/javascript/spa4.md'},
    {title : 'MVW framework없이 SPA구현 5 (다국어 지원)', fileUrl : '/javascript/spa5.md'},
    {title : 'MVW framework없이 SPA구현 6 (Service구현)', fileUrl : '/javascript/spa6.md'},
    {title : 'Javascript 프록시 ', fileUrl : '/javascript/js-proxy.md'},
    {title : 'Javascript의 Event Loop ', fileUrl : '/javascript/js-eventloop.md'},
    {title : 'Javascript의 캡슐화', fileUrl : '/javascript/capsulation.md'},
    {title : 'Garbage Collection', fileUrl : '/javascript/garbage-collection.md'},
    {title : 'IP 및 URL의 유효성 검사', fileUrl : '/javascript/regular-expression.md'},
    {title : 'Cookie 사용', fileUrl : '/javascript/use-cookie.md'},
    {title : 'ES6 편리한 기능', fileUrl : '/javascript/es6-convenient.md'},
    {title : 'Javascript bit 연산', fileUrl : '/javascript/bit-operation.md'},
    {title : 'HTML 팝업창 띄우기', fileUrl : '/javascript/html-popup.md'},
    {title : '구글맵 API 사용하기', fileUrl : '/javascript/google-map.md'},
    {title : 'CAPTCHA 사용하기', fileUrl : '/javascript/captcha.md'},
  ],
  css : [
    {title : 'Responsive Web 구현', fileUrl : '/css/responsive-web.md'},
    {title : '반응형 웹에서 CSS 중앙정렬 기법', fileUrl : '/css/center-align.md'},
    {title : 'flexbox를 사용한 Image 중앙에 위치시키기', fileUrl : '/css/flexbox-center-img.md'},
    {title : 'Image 회전 Animation 적용', fileUrl : '/css/rotate-animation.md'},
    {title : 'CSS Browser hack', fileUrl : '/css/browser-hack.md'},
    {title : '크로스 브라우징 관련 참고', fileUrl : '/css/cross-browsing.md'},
    {title : 'LESS 사용', fileUrl : '/css/less.md'},
    {title : 'float 속성 이해', fileUrl : '/css/float.md'}
  ],
  polymer : [
    {title : 'Web Component란 무엇인가', fileUrl : '/polymer/web-component.md'},
    {title : 'Polymer가이드', fileUrl : '/polymer/polymer-guide.md'},
    {title : 'Polymer Function', fileUrl : '/polymer/polymer-function.md'},
    {title : 'Polymer Observe', fileUrl : '/polymer/polymer-observe.md'},
  ],
  nodejs : [
    {title : 'Socket 서버 구현 1 (Master & Worker Cluster 관리)', fileUrl : '/nodejs/socket-server1.md'},
    {title : 'Socket 서버 구현 2 (Socket Server 실행 및 Socket Router 구현)', fileUrl : '/nodejs/socket-server2.md'},
    {title : 'Socket 서버 구현 3 (Logging)', fileUrl : '/nodejs/socket-server3.md'},
    {title : 'Socket 서버 구현 4 (Redis Client)', fileUrl : '/nodejs/socket-server4.md'},
    {title : 'Socket 서버 구현 5 (Zookeeper Client, Kafka Producer)', fileUrl : '/nodejs/socket-server5.md'},
    {title : 'Socket 서버 구현 6 (http Request)', fileUrl : '/nodejs/socket-server6.md'},
    {title : 'http proxy 서버 구현하기', fileUrl : '/nodejs/http-proxy.md'},
    {title : 'NodeJS 파일 읽기 및 쓰기에 필요한 모든 내용', fileUrl : '/nodejs/howto-file-read-write.md'}
  ],
  backend : [
    {title : 'Redis 사용 이점', fileUrl : '/backend/redis.md'},
    {title : 'Redis Cluster 서버 이전 프로세스', fileUrl : '/backend/redis-cluster-server-change.md'},
    {title : '분산 메시징 시스템 Kafka', fileUrl : '/backend/kafka.md'},
    {title : 'NoSQL Couchbase DB', fileUrl : '/backend/couchbase.md'},
    {title : 'Nginx Config 설정 1', fileUrl : '/backend/nginx_config_1.md'},
    {title : 'Nginx Config 설정 2', fileUrl : '/backend/nginx_config_2.md'},
    {title : 'Nginx 로그 포맷 설정', fileUrl : '/backend/nginx_log.md'},
    {title : 'tcpdump 사용', fileUrl : '/backend/tcpdump.md'},
    {title : 'linux 프로세스 실행 옵션', fileUrl : '/backend/linux-process-execute.md'},
    {title : 'netcat을 사용한 udp 포트 연결 체크', fileUrl : '/backend/udp-port-check.md'},
    {title : 'Firebase Realtime DB사용', fileUrl : '/backend/firebase-realtime-db.md'},
    {title : 'Firebase Realtime DB사용2', fileUrl : '/backend/firebase-realtime-db2.md'},
    {title : 'Firebase 인증', fileUrl : '/backend/firebase-auth.md'}
  ],
  patterns : [
    {title : 'Template Method Pattern', fileUrl : '/patterns/template-method-pattern.md'},
    {title : 'Composite Pattern', fileUrl : '/patterns/composite-pattern.md'},
    {title : 'Observer Pattern', fileUrl : '/patterns/observer-pattern.md'},
    {title : 'Memento Pattern', fileUrl : '/patterns/memento-pattern.md'},
    {title : 'State Pattern', fileUrl : '/patterns/state-pattern.md'},
    {title : 'Builder Pattern', fileUrl : '/patterns/builder-pattern.md'},
    {title : 'Strategy Pattern', fileUrl : '/patterns/strategy-pattern.md'},
    {title : 'Decorator Pattern', fileUrl : '/patterns/decorator-pattern.md'},
    {title : 'Bridge Pattern', fileUrl : '/patterns/bridge-pattern.md'},
    {title : 'Factory Method Pattern', fileUrl : '/patterns/factory-method.md'},
    {title : 'Throttle & Debounce', fileUrl : '/patterns/throttle-debounce.md'},
    {title : 'JS Object Copy', fileUrl : '/patterns/js-object-copy.md'},
    {title : 'JS array modify by index', fileUrl: '/patterns/js-mod-by-index.md'}
  ],
  algorithm : [
    {title : 'Hash Table', fileUrl : '/algorithm/hashtable.md'},
    {title : '깊이 우선 탐색 (DFS, Depth-First Search)', fileUrl : '/algorithm/dfs.md'},
    {title : '너비 우선 탐색 (BFS, Breadth-First Search)', fileUrl : '/algorithm/bfs.md'},
    {title : 'Javascript로 이진탐색트리 구현하기', fileUrl : '/algorithm/binary-search-tree.md'},
    {title : '이진트리가 이진탐색트리인지 판별하기', fileUrl : '/algorithm/check-binary-search-tree.md'},
    {title : '동적 프로그래밍 (dynamic programming)', fileUrl : '/algorithm/dynamic-programming.md'},
    {title : '버블정렬과 선택정렬 (bubble sort, selection sort)', fileUrl : '/algorithm/bubble-selection-sort.md'},
    {title : '퀵 정렬 (quick sort)', fileUrl : '/algorithm/quick-sort.md'},
    {title : '합병 정렬 (merge sort)', fileUrl : '/algorithm/merge-sort.md'},
    {title : '이진 탐색 알고리즘', fileUrl : '/algorithm/binary-search.md'}
  ],
  webrtc : [
    {title : 'WebRTC Peer 구현', fileUrl : '/webrtc/rtcpeer_implement.md'},
    {title : 'WebRTC relay로만 동작하도록 변경하기', fileUrl : '/webrtc/howto_webrtc_relay_only.md'},
    {title : 'TURN/STUN서버 설정', fileUrl : '/webrtc/turnserver-config.md'},
    {title : 'TURN Server monitor Process 구현', fileUrl : '/webrtc/turnserver_monitor_process.md'}
  ]
};
